config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  resources :posts do
      resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :post, :body, presence: true
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :body, presence: true
  has_many :comments, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    post = Post.find(params[:post_id])
    @comments = post.comments
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    post = Post.find(params[:post_id])
    @comment = post.comments.find(params[:id])
  end

  # GET /comments/new
  def new
    post = Post.find(params[:post_id])
    @comment = post.comments.build
  end

  # GET /comments/1/edit
  def edit
    post = Post.find(params[:post_id])
    @comment = post.comments.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    post = Post.find(params[:post_id])
    @comment = post.comments.create(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to ([@comment.post, @comment]), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
        format.js #create.js.erb
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    post = Post.find(params[:post_id])
    @comment = post.comments.find(params[:id])
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to ([@comment.post, @comment]), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    post = Post.find(params[:post_id])
   #2nd you retrieve the comment thanks to params[:id]
    @comment = post.comments.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to post, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:post_id, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
end
  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
end
  # GET /posts/new
  def new
    @post = current_user.posts.build
    #@post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
<p><strong>Posted <%=time_ago_in_words(comment.created_at)%> ago</strong>
<table align="center">
    <tr>
  <td><%= h(comment.body) %></td>
  <td><%= link_to 'Edit', edit_post_comment_path(comment.post, comment) %></td>
  <td><%= link_to 'Destroy', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>
</table></p>
<%end %>

app/views/comments/_form.html.erb
<%= form_for([@comment.post, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
var new_comment = $("<%= j(render(@comment))%>").hide();
$('#comments').prepend(new_comment);
$('#comment_<%= @comment.id %>').fadeIn('slow');
$('#new_comment')[0].reset();

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', [@comment.post, @comment] %> |
<%= link_to 'Back', @post %>

app/views/comments/index.html.erb
<div style="text-align: center;">
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table align="center">
  <thead>
    <tr>
      
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', [comment.post, comment] %></td>
        <td><%= link_to 'Edit', edit_post_comment_path(comment.post, comment) %></td>
        <td><%= link_to 'Destroy', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_post_comment_path %>
</div>>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', post_comments_path(@comment.post) %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_post_comment_path(@comment.post, @comment) %> |
<%= link_to 'Back', post_comments_path(@comment.post) %>

app/views/layouts/_footer.html.erb
<!DOCTYPE html>
<html>

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Login, Sign up Header</title>

  <link rel="stylesheet" href="/assests/stylesheets/demo.css">
  <link rel="stylesheet" href="/assests/stylesheets/header-login-signup.css">
  <link href='http://fonts.googleapis.com/css?family=Cookie' rel='stylesheet' type='text/css'>

</head>

<body style="padding-top: 20px;">

<footer class="header-login-signup">

  <div>

    <h1 style="font: normal 28px Cookie, Arial, Helvetica, sans-serif; color: red; line-height: 40px; margin: 0; text-align: center;"><a href="http://unm.edu">University of New Mexico</a></h1>

  

  </div>

</footer>


</body>

</html>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Login, Sign up Header</title>

  <link rel="stylesheet" href="/assests/stylesheets/demo.css">
  <link rel="stylesheet" href="/assests/stylesheets/header-login-signup.css">
  <link href='http://fonts.googleapis.com/css?family=Cookie' rel='stylesheet' type='text/css'>

</head>

<body>

<header class="header-login-signup">

  <div class="header-limiter">

    <h1><a href="#">ECE595<span>HW3</span></a></h1>

    <nav>
      <a href="http://localhost:3000">Home</a>
      <a href="/posts" class="selected">Posts</a>
      
    </nav>

    <ul>
      <!--<li><a href="/users/sign_in">Login</a></li>
      <li><a href="/users/sign_up">Sign up</a></li>-->
      <% if user_signed_in? %>
        <li>
            <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
        </li>
      <% else %>
        <li>
            <%= link_to('Login', new_user_session_path)  %>  
            <%= link_to('SignUp', new_user_registration_path)  %> 
        </li>
      <% end %>
    </ul>

  </div>

</header>




<!-- Demo ads. Please ignore and remove. -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="http://cdn.tutorialzine.com/misc/enhance/v3.js" async></script>

</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
  	<%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<%= div_for @post do%>
<h2><%= h(@post.title)%></h2>
<%= simple_format h(@post.body) %>
<% end %>

app/views/posts/edit.html.erb
<div style="text-align: center;">
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<div id-"postsPage" style="text-align: center;">
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table align="center" width="100%" style="text-align: left;">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>
</div>

app/views/posts/new.html.erb
<div style="text-align: center;">
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<div style="text-align: center;">
<p id="notice"><%= notice %></p>

<%= render @post %>
<h2>Comments</h2>
<div id="comments">
  <%= render @post.comments.reverse %>
</div>
<%= form_for [@post, Comment.new], remote: true do |f| %>
    <p>
    <%= f.label :body, "New Comment" %><br/>
    <%= f.text_area :body %>
    </p>
    <p><%= f.submit "Add Comment"%></p>
<% end %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
</div>